In [1]:
print('hello')

hello


#Numpy的导入：针对矩阵/向量的运算 ----  Numpy import： For matrix and vector computations
##需求：矩阵相加
        [0, 1, 4] + [0, 1, 8] = [0, 2, 12]

In [2]:
import numpy as np

In [3]:
def npSum(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    return a+b

In [4]:
npSum(3)

array([ 0,  2, 12])

In [8]:
npSum(1000)[-3:]

array([992020982, 995007996, 998001000])

In [6]:
%timeit npSum(1000)

7.39 μs ± 75 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [11]:
def npSumBig(n):
    a = np.arange(n, dtype = np.int64) ** 2
    b = np.arange(n, dtype = np.int64) ** 3
    return a+b

In [12]:
npSumBig(1000)[-3:]

array([992020982, 995007996, 998001000], dtype=int64)