In [1]:
import numpy as np

In [2]:
a1 = np.arange(10,41,10)

In [3]:
a1

array([10, 20, 30, 40])

In [4]:
a2 = np.array([11, 22, 33, 44, 15, 26, 37, 48]).reshape(2,4)

In [5]:
a2

array([[11, 22, 33, 44],
       [15, 26, 37, 48]])

In [8]:
arr = np.array(['a', 'bc'], dtype='S2')  # 2 字节长度的字节串
arr2 = np.array(['你好', '世界'], dtype='U2')  # 注意：U 表示 Unicode，但长度是指字符数，不是字节数

In [9]:
arr

array([b'a', b'bc'], dtype='|S2')

In [10]:
arr2

array(['你好', '世界'], dtype='<U2')

In [6]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])

print(a) # 从某个索引处开始切割

print('从数组索引 a[1:] 处开始切割')

print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
从数组索引 a[1:] 处开始切割
[[3 4 5]
 [4 5 6]]


In [9]:
a = np.arange(9)

In [13]:
print ('第一个数组：')
print (a) 
print ('\n')

第一个数组：
[0 1 2 3 4 5 6 7 8]




In [14]:
print ('将数组分为三个大小相等的子数组：')

b = np.split(a,3)

print (b)

print ('\n')

将数组分为三个大小相等的子数组：
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]




In [15]:
print ('将数组在一维数组中表明的位置分割：')

b = np.split(a,[4,7])

print (b)

将数组在一维数组中表明的位置分割：
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [2]:
a = np.array([0.25, 1.33, 1, 100])

print ('我们的数组是：')

print (a)

print ('\n')

print ('调用 reciprocal 函数：')

print (np.reciprocal(a))

我们的数组是：
[  0.25   1.33   1.   100.  ]


调用 reciprocal 函数：
[4.        0.7518797 1.        0.01     ]


In [3]:

a = np.array([[1,2],[3,4]])

b = np.array([[11,12],[13,14]])

print(np.dot(a,b))


[[37 40]
 [85 92]]


In [4]:
np.add(a, b)

array([[12, 14],
       [16, 18]])