# Create an array  
## Create a one-dimensional array

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5,6])

In [3]:
arr1

array([1, 2, 3, 4, 5, 6])

In [4]:
[1,2,3,4,5,6]

[1, 2, 3, 4, 5, 6]

In [5]:
print(arr1)

[1 2 3 4 5 6]


In [6]:
print('arr1\'s dimension: ', arr1.ndim)
print('arr1\'s shape: ', arr1.shape)
print('arr1\'s datatype: ', arr1.dtype)

arr1's dimension:  1
arr1's shape:  (6,)
arr1's datatype:  int32


In [7]:
arr2 = np.array([1,2,3,4,4.5,5,6,7])
arr2.dtype

dtype('float64')

In [8]:
arr3 = np.arange(1,2.01,0.01)

In [9]:
arr3

array([1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09, 1.1 ,
       1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 , 1.21,
       1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31, 1.32,
       1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42, 1.43,
       1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.5 , 1.51, 1.52, 1.53, 1.54,
       1.55, 1.56, 1.57, 1.58, 1.59, 1.6 , 1.61, 1.62, 1.63, 1.64, 1.65,
       1.66, 1.67, 1.68, 1.69, 1.7 , 1.71, 1.72, 1.73, 1.74, 1.75, 1.76,
       1.77, 1.78, 1.79, 1.8 , 1.81, 1.82, 1.83, 1.84, 1.85, 1.86, 1.87,
       1.88, 1.89, 1.9 , 1.91, 1.92, 1.93, 1.94, 1.95, 1.96, 1.97, 1.98,
       1.99, 2.  ])

## multiple-dimension

In [10]:
arr4 = np.array([np.array([1,2,3]),np.array([4,5,6]),np.array([7,8,9])])

In [11]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr5 = np.array([np.arange(1,4), np.arange(4,7), np.arange(7,10)])

In [13]:
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr5.ndim

2

In [15]:
arr5.shape

(3, 3)

In [16]:
arr6 = np.array(
[
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]
)

In [17]:
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
arr6.shape

(3, 4)

In [22]:
np.zeros

<function numpy.zeros>

zeros(shape, dtype=float, order='C', *, like=None)  

Return a new array of given shape and type, filled with zeros.  

Parameters  
----------  
shape : int or tuple of ints  
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.  
dtype : data-type, optional  
    The desired data-type for the array, e.g., `numpy.int8`.  Default is `numpy.float64`.  
order : {'C', 'F'}, optional, default: 'C'  
    Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.

In [26]:
arr7 = np.zeros((4,3))

In [27]:
arr7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
arr7.dtype

dtype('float64')

In [29]:
arr8 = np.zeros((4,5),dtype = int)

In [30]:
arr8

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [31]:
arr8.dtype

dtype('int32')

In [32]:
arr9 = np.zeros_like(arr4)

In [33]:
arr9

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
np.ones

<function numpy.ones(shape, dtype=None, order='C', *, like=None)>

In [35]:
arr10 = np.full((4,5),'Yes')

In [36]:
arr10

array([['Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Yes']], dtype='<U3')

In [38]:
np.eye

<function numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)>

Signature: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)  
Docstring:  
Return a 2-D array with ones on the diagonal and zeros elsewhere.  

Parameters  
----------  
N : int  
  Number of rows in the output.  
M : int, optional  
  Number of columns in the output. If None, defaults to `N`.  
k : int, optional  
  Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.

In [40]:
arr11 = np.eye(7)
arr12 = np.eye(7,5)
arr11

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [41]:
arr12

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
arr13 = np.eye(7, k=2)

In [43]:
arr13

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [45]:
arr14 = np.empty((3,3))

In [46]:
arr14

array([[0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 5.95e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [47]:
arr15 = np.random.random((4,3))

In [48]:
arr15

array([[0.96630575, 0.16484555, 0.31184004],
       [0.00277031, 0.25238522, 0.17079391],
       [0.31239058, 0.87860687, 0.38747132],
       [0.45970471, 0.95326556, 0.6560802 ]])

In [52]:
arr16 = np.arange(1,25)

In [53]:
arr16

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [54]:
arr17 = arr16.reshape((2,3,4))

In [55]:
arr17

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

# The indexing and slicing of arrays.  
## Indexing and slicing of one-dimensional arrays (refer to lists)

In [57]:
a1 = np.arange(9)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
a1[-1]

8

In [59]:
a1[1:-1]

array([1, 2, 3, 4, 5, 6, 7])

In [60]:
a1[-1::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

## Multiple dimensional arrays

In [61]:
a2 = np.arange(9).reshape(3,3)

In [62]:
a2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
a2[1,2] #Nested list cannot be accessed using multidimensional indexing

5

In [64]:
a3 = np.random.randint(1,100,27).reshape((3,3,3))

In [65]:
a3

array([[[82, 67, 30],
        [82, 47, 40],
        [62, 58, 51]],

       [[76,  2, 60],
        [65, 78, 30],
        [72, 23, 85]],

       [[54, 50, 34],
        [62, 38, 49],
        [95, 44, 48]]])

In [66]:
a3[1,1,2]

30

In [67]:
a3[1]

array([[76,  2, 60],
       [65, 78, 30],
       [72, 23, 85]])

In [68]:
a4 = np.arange(1,36).reshape(5,7)

In [69]:
a4

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

In [70]:
a4[0:2,0:]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [72]:
a4[:2] #Slice the rows directly

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [75]:
a4[5:] #Attention: When slicing only the final dimension, leading dimensions must remain intact

array([], shape=(0, 7), dtype=int32)

In [76]:
a4[:,5:]

array([[ 6,  7],
       [13, 14],
       [20, 21],
       [27, 28],
       [34, 35]])

In [77]:
#reverse
a4[::-1,::-1]

array([[35, 34, 33, 32, 31, 30, 29],
       [28, 27, 26, 25, 24, 23, 22],
       [21, 20, 19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10,  9,  8],
       [ 7,  6,  5,  4,  3,  2,  1]])

In [79]:
a4[2:4,2:4] = 0
a4

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16,  0,  0, 19, 20, 21],
       [22, 23,  0,  0, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

### Magic index  
Using arrays/lists as indices of arrays: Access by position

In [117]:
x1 = np.arange(10)

In [109]:
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
x1[[3,4,7]]

array([3, 4, 7])

In [85]:
index1 = np.array([[0,2],[1,3]])

In [86]:
x1[index1]

array([[0, 2],
       [1, 3]])

In [87]:
x2 = np.arange(20).reshape((4,5))

In [88]:
x2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [89]:
x2[0::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [90]:
x2[[0,2]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [91]:
x2[:,[1,3,4]]

array([[ 1,  3,  4],
       [ 6,  8,  9],
       [11, 13, 14],
       [16, 18, 19]])

In [92]:
x2[[0,2,3],[0,1,4]]

array([ 0, 11, 19])

### Boolean indexing
Access by condition

In [93]:
#Find elements greater than 4

In [110]:
x1[x1>4]

array([5, 6, 7, 8, 9])

In [111]:
x1 > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [112]:
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
#Convert numbers greater than 4 in x1 to 1, and numbers less than or equal to 4 to 0
#(discretization of continuous variables)
x1[x1<=4] = 0
x1[x1>4] = 1

In [119]:
x1

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [120]:
x2 > 5

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [121]:
x2[x2>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [122]:
x2[:,3][x2[:,3]>5]

array([ 8, 13, 18])

In [123]:
#Compound condition
x2[:,3][(x2[:,3] % 2 == 1) | (x2[:,3] > 10)]

array([ 3, 13, 18])