In [1]:
 import numpy as np

# 1. Array dimension adjustment
## 1.1 Dimension augmentation

In [2]:
array01 = np.arange(24)

In [3]:
array01

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [5]:
array01.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [6]:
array02 = np.arange(35)

In [8]:
array02.shape = (5,7)

In [9]:
array02

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [10]:
array03 = np.arange(30)
array03

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
array04 = array03.resize(6,5)
array03

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [12]:
print(array04)

None


In [13]:
array05 = array03.reshape(3,10)
array05

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [14]:
array03[0,0] = 999
array03

array([[999,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29]])

In [15]:
array05

array([[999,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]])

In [16]:
array06 = array05.copy()

In [17]:
array06

array([[999,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]])

In [18]:
array06[0,0] = 100

In [19]:
array05

array([[999,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]])

In [20]:
array06

array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]])

## Array dimension reduction

In [21]:
arr1 = np.arange(30).reshape((5,6))

In [22]:
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [23]:
arr2 = arr1.ravel()
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
arr2[0] = -1

In [25]:
arr1

array([[-1,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [26]:
arr3 = arr1.flatten()

In [27]:
arr3[0] = 999

In [28]:
arr3

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [29]:
arr1

array([[-1,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [31]:
for iRow in range(arr1.shape[0]):
    for iCol in range(arr1.shape[1]):
        print(arr1[iRow, iCol],end = '\t')

-1	1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	20	21	22	23	24	25	26	27	28	29	

In [34]:
for item in arr1.flatten():
    print(item,end = '\t')

-1	1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	20	21	22	23	24	25	26	27	28	29	

In [38]:
for item in arr1.flat:
    print(item,end = '\t')

-1	1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	20	21	22	23	24	25	26	27	28	29	

In [39]:
 arr1.flat

In [40]:
for item in arr1:
    print(item, end = '\t')

[-1  1  2  3  4  5]	[ 6  7  8  9 10 11]	[12 13 14 15 16 17]	[18 19 20 21 22 23]	[24 25 26 27 28 29]	

In [42]:
arr4 = arr1.reshape(30,1)
arr4

array([[-1],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [43]:
 arr5 = arr1.reshape(1,30)

In [44]:
arr5

array([[-1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [45]:
arr2

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [46]:
arr6 = arr1.reshape(30)
arr6

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [49]:
arr7 = arr1.reshape(-1)

In [50]:
arr7

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## Array transposition

In [54]:
arr8 = arr1.transpose() #a view
arr8

array([[-1,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [55]:
arr9 = arr1.T #a view

In [56]:
arr9

array([[-1,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

# Array combination and splitting
## combination
### Horizental combination

In [57]:
m1 = np.arange(9).reshape((3,3))

In [58]:
m1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
m2 = m1 * 2

In [60]:
m2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [61]:
m1 + m2

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [67]:
r1 = np.hstack((m1,m2))#A copy
r1

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [68]:
r2 = np.concatenate((m1,m2), axis = 1)#A copy
r2

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [69]:
r1 == r2

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [70]:
r1[0,0] = 100

In [71]:
r1

array([[100,   1,   2,   0,   2,   4],
       [  3,   4,   5,   6,   8,  10],
       [  6,   7,   8,  12,  14,  16]])

In [72]:
m1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
m2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [74]:
r2

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

### Vertical concatenation

In [76]:
r3 = np.vstack((m1,m2))

In [77]:
r3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [78]:
r4 = np.concatenate((m1,m2), axis = 0)

In [79]:
r4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

### Depth concatenation

In [82]:
r5 = np.dstack((m1,m2)) #Change the dimensions
r5

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [83]:
r5.shape

(3, 3, 2)

In [86]:
# column_stack and hstack
r7 = np.hstack((m1,m2))
r7

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [87]:
r7a = np.column_stack((m1,m2))
r7a

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [88]:
n1 = np.arange(3)
n1

array([0, 1, 2])

In [90]:
n2 = n1 * 5
n2

array([ 0,  5, 10])

In [91]:
r8 = np.hstack((n1,n2))
r8

array([ 0,  1,  2,  0,  5, 10])

In [93]:
r8a = np.column_stack((n1,n2))
r8a

array([[ 0,  0],
       [ 1,  5],
       [ 2, 10]])

In [95]:
#row_stack and v_stack
r10 = np.vstack((n1,n2)) #same
r10

array([[ 0,  1,  2],
       [ 0,  5, 10]])

In [97]:
r10a = np.row_stack((n1,n2))
r10a

array([[ 0,  1,  2],
       [ 0,  5, 10]])

# Array splitting
## horizental splitting

In [100]:
as1 = np.arange(9).reshape((3,3))
as1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [101]:
as2 = np.arange(9).reshape((3,-1))
as2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
re1 = np.hsplit(as1,3)
re1

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [103]:
type(re1)

list

In [104]:
for item in re1:
    print(item)
    print(item.shape)

[[0]
 [3]
 [6]]
(3, 1)
[[1]
 [4]
 [7]]
(3, 1)
[[2]
 [5]
 [8]]
(3, 1)


In [105]:
re1a = np.split(as1,3,axis = 1)
re1a

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

## Vertical splitting

In [107]:
re3 =  np.vsplit(as1,3)
re3

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [109]:
for item in re3:
    print(item)
    print(item.shape)

[[0 1 2]]
(1, 3)
[[3 4 5]]
(1, 3)
[[6 7 8]]
(1, 3)


In [110]:
re3a = np.split(as1,3)
re3a

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

## Depth splitting

In [111]:
as2 = np.arange(64).reshape(4,4,4)
as2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [112]:
re5 = np.dsplit(as2,2)
re5

[array([[[ 0,  1],
         [ 4,  5],
         [ 8,  9],
         [12, 13]],
 
        [[16, 17],
         [20, 21],
         [24, 25],
         [28, 29]],
 
        [[32, 33],
         [36, 37],
         [40, 41],
         [44, 45]],
 
        [[48, 49],
         [52, 53],
         [56, 57],
         [60, 61]]]),
 array([[[ 2,  3],
         [ 6,  7],
         [10, 11],
         [14, 15]],
 
        [[18, 19],
         [22, 23],
         [26, 27],
         [30, 31]],
 
        [[34, 35],
         [38, 39],
         [42, 43],
         [46, 47]],
 
        [[50, 51],
         [54, 55],
         [58, 59],
         [62, 63]]])]