In [7]:
import numpy as np

# File reading and writing
## file writing

In [8]:
arr1 = np.arange(35).reshape(5,7)

In [9]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [10]:
np.savetxt("1.csv", arr1, fmt = '%d', delimiter = ',')

In [11]:
#./current path ../father
np.savetxt("Datebase/1.csv", arr1, fmt = '%d', delimiter = ',')

## file reading

In [12]:
Close = np.loadtxt('Datebase/data.csv', delimiter = ',', skiprows = 1, usecols = 6, encoding = 'gbk')

In [13]:
Close

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [14]:
Close1,Volumn1 = np.loadtxt('Datebase/data.csv',
                            delimiter = ',',
                            skiprows = 1,
                            usecols = (6,7),
                            unpack = True,
                            encoding = 'gbk')

In [15]:
Close

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [16]:
Volumn1

array([21144800., 13473000., 15236800.,  9242600., 14064100., 11494200.,
       17322100., 13608500., 17240800., 33162400., 13127500., 11086200.,
       10149000., 17184100., 18949000., 29144500., 31162200., 23994700.,
       17853500., 13572000., 14395400., 16290300., 21521000., 17885200.,
       16188000., 19504300., 12718000., 16192700., 18138800., 16824200.])

# Statistical analysis based on Numpy function
##  Central tendency

In [17]:
#The mean of the closing prices
var1 = np.mean(Close)

In [18]:
var1

351.0376666666667

In [19]:
#Compute the weighted mean of closing prices with trading volume as the weighting factor
vwap = np.average(Close, weights = Volumn1)

In [20]:
vwap

350.5895493532009

In [21]:
var3 =  np.median(Close)

In [22]:
var3

352.055

In [23]:
Sorted_Close = np.sort(Close, axis = 0)
Sorted_Close

array([336.1 , 338.61, 339.32, 342.62, 342.88, 343.44, 344.32, 345.03,
       346.5 , 346.67, 348.16, 349.31, 350.56, 351.88, 351.99, 352.12,
       352.47, 353.21, 354.54, 355.2 , 355.36, 355.76, 356.85, 358.16,
       358.3 , 359.18, 359.56, 359.9 , 360.  , 363.13])

In [24]:
(Sorted_Close[14] + Sorted_Close[15]) / 2

352.055

In [25]:
# mode
import pandas as pd

In [26]:
arr1 = np.random.randint(1, 10, 20)
arr1

array([5, 7, 7, 6, 2, 5, 8, 9, 5, 7, 2, 2, 1, 8, 5, 5, 7, 9, 6, 4])

In [27]:
ser1 = pd.Series(arr1)
ser1

0     5
1     7
2     7
3     6
4     2
5     5
6     8
7     9
8     5
9     7
10    2
11    2
12    1
13    8
14    5
15    5
16    7
17    9
18    6
19    4
dtype: int32

In [28]:
ser1.mode()

0    5
dtype: int32

# measure of dispersion

In [29]:
np.max(Close1)

363.13

In [30]:
np.min(Close1)

336.1

In [31]:
round(np.ptp(Close1), 2)

27.03

In [32]:
print('variance of closing price : ', np.var(Close))

variance of closing price :  50.126517888888884


In [33]:
print('Standard deviation of closing price : ', np.std(Close))

Standard deviation of closing price :  7.080008325481608


In [35]:
#Coefficient of Variation(CV)  = Standard deviation / average
print('Coefficient of Variation of Closing Price : ', np.std(Close) / np.mean(Close))

Coefficient of Variation of Closing Price :  0.020168799527158835


Compute returns

In [36]:
#Difference Array
diff_Close = np.diff(Close)

In [37]:
diff_Close

array([  3.22,   5.71,  -0.71,  -0.88,   3.06,   5.38,   3.32,   2.96,
        -3.62,   2.31,   2.33,   0.72,   3.23,  -4.83,  -7.74, -11.95,
         4.01,   0.26,   5.28,   5.05,  -3.9 ,   2.81,   7.44,   0.44,
        -4.64,   0.4 ,  -3.29,  -5.8 ,   5.32])

In [38]:
len(Close)

30

In [39]:
len(diff_Close)

29

In [40]:
#Returns(Simple)
returns = diff_Close/Close[:1]

In [41]:
returns

array([ 0.00958048,  0.01698899, -0.00211247, -0.00261827,  0.00910443,
        0.01600714,  0.00987801,  0.0088069 , -0.0107706 ,  0.00687295,
        0.00693246,  0.00214222,  0.00961024, -0.01437072, -0.02302886,
       -0.03555489,  0.01193097,  0.00077358,  0.01570961,  0.01502529,
       -0.01160369,  0.00836061,  0.02213627,  0.00130913, -0.01380542,
        0.00119012, -0.00978875, -0.01725677,  0.01582862])

In [44]:
#Extract the array of positive returns
preturns = returns.compress(returns > 0)

In [45]:
preturns

array([0.00958048, 0.01698899, 0.00910443, 0.01600714, 0.00987801,
       0.0088069 , 0.00687295, 0.00693246, 0.00214222, 0.00961024,
       0.01193097, 0.00077358, 0.01570961, 0.01502529, 0.00836061,
       0.02213627, 0.00130913, 0.00119012, 0.01582862])

In [46]:
p1 = returns[returns > 0]

In [47]:
p1

array([0.00958048, 0.01698899, 0.00910443, 0.01600714, 0.00987801,
       0.0088069 , 0.00687295, 0.00693246, 0.00214222, 0.00961024,
       0.01193097, 0.00077358, 0.01570961, 0.01502529, 0.00836061,
       0.02213627, 0.00130913, 0.00119012, 0.01582862])

In [48]:
p_index = np.where(returns > 0)

In [49]:
p_index

(array([ 0,  1,  4,  5,  6,  7,  9, 10, 11, 12, 16, 17, 18, 19, 21, 22, 23,
        25, 28], dtype=int64),)

In [50]:
p2 = returns[p_index]

In [51]:
p2

array([0.00958048, 0.01698899, 0.00910443, 0.01600714, 0.00987801,
       0.0088069 , 0.00687295, 0.00693246, 0.00214222, 0.00961024,
       0.01193097, 0.00077358, 0.01570961, 0.01502529, 0.00836061,
       0.02213627, 0.00130913, 0.00119012, 0.01582862])

In [52]:
p1 == p2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [53]:
logreturns = np.diff(np.log(Close))

In [54]:
logreturns

array([ 0.00953488,  0.01668775, -0.00205991, -0.00255903,  0.00887039,
        0.01540739,  0.0093908 ,  0.0082988 , -0.01015864,  0.00649435,
        0.00650813,  0.00200256,  0.00893468, -0.01339027, -0.02183875,
       -0.03468287,  0.01177296,  0.00075857,  0.01528161,  0.01440064,
       -0.011103  ,  0.00801225,  0.02090904,  0.00122297, -0.01297267,
        0.00112499, -0.00929083, -0.01659219,  0.01522945])

In [55]:
#Volatility
v_log = np.std(logreturns) / np.mean(logreturns)

In [56]:
v_log

8.14354630702448

In [57]:
#Years Vol
y_wave = v_log / np.sqrt(1/252)

In [58]:
y_wave

129.27478991115132

In [59]:
#Months Vol
m_wave = v_log / np.sqrt(1 / 12)

In [60]:
m_wave

28.210071915112596

# Compare the average values of Apple stock from Monday to Friday.

In [61]:
from datetime import datetime

In [62]:
?datetime.strptime

Docstring: string, format -> new datetime parsed from a string (like time.strptime()).
Type:      builtin_function_or_method

In [63]:
import time

In [65]:
?time.strptime

Docstring:
strptime(string, format) -> struct_time

Parse a string to a time tuple according to a format specification.
See the library reference manual for formatting codes (same as
strftime()).

Commonly used format codes:

%Y  Year with century as a decimal number.
%m  Month as a decimal number [01,12].
%d  Day of the month as a decimal number [01,31].
%H  Hour (24-hour clock) as a decimal number [00,23].
%M  Minute as a decimal number [00,59].
%S  Second as a decimal number [00,61].
%z  Time zone offset from UTC.
%a  Locale's abbreviated weekday name.
%A  Locale's full weekday name.
%b  Locale's abbreviated month name.
%B  Locale's full month name.
%c  Locale's appropriate date and time representation.
%I  Hour (12-hour clock) as a decimal number [01,12].
%p  Locale's equivalent of either AM or PM.

Other codes may be available on your platform.  See documentation for
the C library strftime function.
Type:      builtin_function_or_method

In [66]:
date1 = datetime.strptime('2021-09-16', '%Y-%m-%d')

In [67]:
date1

datetime.datetime(2021, 9, 16, 0, 0)

In [68]:
date1.date()

datetime.date(2021, 9, 16)

In [71]:
date1.date().weekday()
#Index of Monday == 0

3

In [72]:
date1.date().isoweekday()

4

In [75]:
eDate = np.loadtxt('Datebase/data.csv',
                   delimiter = ',',
                   skiprows = 1,
                   usecols = 1,
                   dtype = str,
                   encoding = 'GBK'
)

In [76]:
eDate

array(['28-01-2011', '31-01-2011', '01-02-2011', '02-02-2011',
       '03-02-2011', '04-02-2011', '07-02-2011', '08-02-2011',
       '09-02-2011', '10-02-2011', '11-02-2011', '14-02-2011',
       '15-02-2011', '16-02-2011', '17-02-2011', '18-02-2011',
       '22-02-2011', '23-02-2011', '24-02-2011', '25-02-2011',
       '28-02-2011', '01-03-2011', '02-03-2011', '03-03-2011',
       '04-03-2011', '07-03-2011', '08-03-2011', '09-03-2011',
       '10-03-2011', '11-03-2011'], dtype='<U10')

In [78]:
#Convert a date string to the day of the week
datetime.strptime(eDate[0], '%d-%m-%Y').date().isoweekday()

5

In [79]:
eWeek = []

In [80]:
for item in eDate:
    #Iterate through dates
    eWeek.append(datetime.strptime(item, '%d-%m-%Y').date().isoweekday())

In [81]:
eWeek

[5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5]

In [82]:
type(eWeek)

list

In [84]:
eWeek1 = np.array(eWeek)

In [85]:
eWeek1

array([5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 2, 3, 4, 5, 1, 2,
       3, 4, 5, 1, 2, 3, 4, 5])

In [86]:
?np.loadtxt

Signature:
np.loadtxt(
    fname,
    dtype=<class 'float'>,
    comments='#',
    delimiter=None,
    converters=None,
    skiprows=0,
    usecols=None,
    unpack=False,
    ndmin=0,
    encoding='bytes',
    max_rows=None,
    *,
    quotechar=None,
    like=None,
)
Docstring:
Load data from a text file.

Parameters
----------
fname : file, str, pathlib.Path, list of str, generator
    File, filename, list, or generator to read.  If the filename
    extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
    that generators must return bytes or strings. The strings
    in a list or produced by a generator are treated as lines.
dtype : data-type, optional
    Data-type of the resulting array; default: float.  If this is a
    structured data-type, the resulting array will be 1-dimensional, and
    each row will be interpreted as an element of the array.  In this
    case, the number of columns used must match the number of fields in
    the data-type.
comments : str or

In [93]:
#Construct a function that converts dates string to the days of the week.
def dstr2weekday(datestr):
    return datetime.strptime(datestr, '%d-%m-%Y').date().isoweekday()

In [94]:
dstr2weekday(eDate[0])

5

In [95]:
Weekday2,Close2 = np.loadtxt('Datebase/data.csv',
                             delimiter = ',',
                             skiprows = 1,
                             usecols = (1, 6),
                             unpack = True,
                             encoding = 'GBK',
                             converters = {1:dstr2weekday}
)

In [96]:
Weekday2

array([5., 1., 2., 3., 4., 5., 1., 2., 3., 4., 5., 1., 2., 3., 4., 5., 2.,
       3., 4., 5., 1., 2., 3., 4., 5., 1., 2., 3., 4., 5.])

In [97]:
eWeek1

array([5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 2, 3, 4, 5, 1, 2,
       3, 4, 5, 1, 2, 3, 4, 5])

In [98]:
Close2

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [99]:
#Construct an empty array to store the average closing prices from Monday to Friday.
avgs = np.zeros(5)

In [100]:
avgs

array([0., 0., 0., 0., 0.])

In [105]:
for i in range(1, 6):
    #Iterate through Monday to Friday
    indexarray = np.where(Weekday2 == i)
    print(indexarray)
    price = np.take(Close2, indexarray)
    print(price)
    avg = np.mean(price)
    print(avg)
    avgs[i-1] = avg

(array([ 1,  6, 11, 20, 25], dtype=int64),)
[[339.32 351.88 359.18 353.21 355.36]]
351.7900000000001
(array([ 2,  7, 12, 16, 21, 26], dtype=int64),)
[[345.03 355.2  359.9  338.61 349.31 355.76]]
350.63500000000005
(array([ 3,  8, 13, 17, 22, 27], dtype=int64),)
[[344.32 358.16 363.13 342.62 352.12 352.47]]
352.1366666666666
(array([ 4,  9, 14, 18, 23, 28], dtype=int64),)
[[343.44 354.54 358.3  342.88 359.56 346.67]]
350.8983333333333
(array([ 0,  5, 10, 15, 19, 24, 29], dtype=int64),)
[[336.1  346.5  356.85 350.56 348.16 360.   351.99]]
350.0228571428571


In [106]:
print(avgs)

[351.79       350.635      352.13666667 350.89833333 350.02285714]


In [108]:
print('max : ', np.max(avgs), 'day : ', np.argmax(avgs) + 1)

max :  352.1366666666666 day :  3
