# Arithmetic operations in Numpy
## Operations between arrays and scalars

In [1]:
import numpy as np

In [2]:
a1 = np.arange(1,7).reshape(2,3)
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
b = 3

In [4]:
a1 + b

array([[4, 5, 6],
       [7, 8, 9]])

In [6]:
a1 * b

array([[ 3,  6,  9],
       [12, 15, 18]])

# Betweeen arrays and arrays
## Two arrays have identical shapes

In [7]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a2 = a1 * 3

In [9]:
a2

array([[ 3,  6,  9],
       [12, 15, 18]])

In [10]:
a1 + a2

array([[ 4,  8, 12],
       [16, 20, 24]])

## Two arrays have different shapes

In [11]:
a3 = np.random.randint(1, 10, 8).reshape(2,4)

In [12]:
a3

array([[7, 1, 4, 6],
       [1, 1, 7, 7]])

In [13]:
a1 + a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,4) 

In [14]:
a4 = np.array([1,2,3])

In [15]:
a4

array([1, 2, 3])

In [16]:
a4.shape

(3,)

In [19]:
a1.shape

(2, 3)

In [21]:
a1 + a4
#Equal number of columns
#1.Replication for completing calculations  2.Broadcasting

array([[2, 4, 6],
       [5, 7, 9]])

In [23]:
a6 = np.array([[1],[2]])

In [24]:
a6

array([[1],
       [2]])

In [26]:
a1 + a6
#Equal number of rows
#1.Replication for completing calculations  2.Broadcasting

array([[2, 3, 4],
       [6, 7, 8]])

# Matrix operations

In [27]:
m1 = np.array([[0, 1, 2], [3, 4, 5]])

In [28]:
m1

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
m2 = np.array([[10,11],[12,13],[14,15]])

In [30]:
m2

array([[10, 11],
       [12, 13],
       [14, 15]])

In [31]:
np.dot(m1, m2)
#Matrix multiplication

array([[ 40,  43],
       [148, 160]])

## Solving systems of linear equations
鸡兔同笼 35个头，94条腿\
1x + 1y = 35\
2x + 4y = 94\
np.linalg.solve(系数矩阵，结果矩阵）

In [33]:
#Coefficient matrix
arr1 = np.array([[1,1],[2,4]])

In [34]:
arr2 = np.array([35,94])

In [35]:
np.linalg.solve(arr1,arr2)

array([23., 12.])

# Treatment of missing values

In [36]:
array1 = np.array([[1,0,2,-3],[-4,2,8,9]])

In [37]:
array1

array([[ 1,  0,  2, -3],
       [-4,  2,  8,  9]])

In [38]:
array2 = np.sqrt(array1)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_36156\2002090465.py:1: RuntimeWarning: invalid value encountered in sqrt
  array2 = np.sqrt(array1)


In [39]:
array2

array([[1.        , 0.        , 1.41421356,        nan],
       [       nan, 1.41421356, 2.82842712, 3.        ]])

In [40]:
np.nan

nan

In [41]:
np.isnan(array2)

array([[False, False, False,  True],
       [ True, False, False, False]])

In [42]:
array2[np.isnan(array2)]

array([nan, nan])

In [44]:
array2[np.isnan(array2)] = 0

In [45]:
array2

array([[1.        , 0.        , 1.41421356, 0.        ],
       [0.        , 1.41421356, 2.82842712, 3.        ]])